DROP DATABASE IF EXISTS `chats`;

CREATE DATABASE `chats`;

USE `chats`;

CREATE TABLE `users` (
    ID MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    naam VARCHAR(100) NOT NULL,
    wachtwoord VARCHAR(100) NOT NULL
);

CREATE TABLE `berichten` (
    ID MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    bericht TEXT,
    verzenderID MEDIUMINT NOT NULL,
    ontvangerID MEDIUMINT NOT NULL
);